# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 08:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='momouser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='momouser',
            name='last_name',
        ),
    ]
