# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 07:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='momouser',
            name='following',
        ),
        migrations.AddField(
            model_name='momouser',
            name='relation',
            field=models.ManyToManyField(related_name='relation_user_set', through='member.RelationShip', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_from_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_to_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
