# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20170414_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='momouser',
            name='facebook_id',
        ),
    ]
