# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20170402_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='momouser',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
