# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20170419_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='momouser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
