# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 13:36
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20170420_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='momouser',
            name='profile_img',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='headshot/', verbose_name='Headshot'),
        ),
    ]
