# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_auto_20170420_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='momouser',
            name='description',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='momouser',
            name='userid',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
