# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_auto_20170422_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='momouser',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
