# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pin.PinComment')),
                ('photo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pin.PinPhoto')),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pin.Pin')),
            ],
        ),
    ]
