# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 13:36
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20170419_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='post/', verbose_name='post'),
        ),
    ]
