# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('lat', models.DecimalField(decimal_places=3, max_digits=14)),
                ('lng', models.DecimalField(decimal_places=3, max_digits=14)),
            ],
        ),
    ]
