# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_auto_20170414_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='place_id',
            new_name='googlepid',
        ),
    ]
