# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='pin_color',
            field=models.CharField(default='0,0,0', max_length=10),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
