# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pincomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='pincomment',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='pinphoto',
            name='author',
        ),
        migrations.RemoveField(
            model_name='pinphoto',
            name='pin',
        ),
    ]
