# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0003_auto_20170331_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='google_place_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
