# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0004_auto_20170331_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='pinhashtag',
            name='created_date',
        ),
    ]
