# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0005_auto_20170402_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pinhashtag',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
