# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0006_auto_20170402_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='author',
        ),
        migrations.AlterField(
            model_name='pin',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Map'),
        ),
        migrations.DeleteModel(
            name='Map',
        ),
    ]
