# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0008_auto_20170404_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pin',
            old_name='user_map',
            new_name='map',
        ),
    ]
