# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_map_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='name',
            new_name='map_name',
        ),
    ]
