# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20170413_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
