# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20170415_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
