# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_map_updated_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='updated_date',
        ),
        migrations.AlterModelTable(
            name='map',
            table='map_map',
        ),
    ]
