# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_remove_map_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
